app = "telegram-bot-example"  # ← Fly.io сам сгенерирует имя, или задай своё

primary_region = "ams"

[build]
  image = "python:3.10"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
